using System;
using System.Data;
using System.Data.SqlClient;

namespace GestionDecanat.DAL
{
    public class FaculteRepository : BaseRepository { protected override string TableName { get { return "Facultes"; } } protected override string IdColumn { get { return "idFaculte"; } } protected override string[] EditableColumns { get { return new[] { "nomFaculte" }; } } public SqlParameter[] Parameters(string nom) { return new[] { new SqlParameter("@nomFaculte", nom) }; } }
    public class PromotionRepository : BaseRepository { protected override string TableName { get { return "Promotions"; } } protected override string IdColumn { get { return "idPromotion"; } } protected override string[] EditableColumns { get { return new[] { "nomPromotion", "idFaculte" }; } } protected override string SelectQuery { get { return "SELECT p.idPromotion,p.nomPromotion,p.idFaculte,f.nomFaculte FROM Promotions p INNER JOIN Facultes f ON f.idFaculte=p.idFaculte ORDER BY p.idPromotion DESC"; } } public SqlParameter[] Parameters(string nom, int faculte) { return new[] { new SqlParameter("@nomPromotion", nom), new SqlParameter("@idFaculte", faculte) }; } }
    public class AnneeAcademiqueRepository : BaseRepository { protected override string TableName { get { return "AnneesAcademiques"; } } protected override string IdColumn { get { return "idAnnee"; } } protected override string[] EditableColumns { get { return new[] { "libelle", "estActive" }; } } public SqlParameter[] Parameters(string libelle, bool active) { return new[] { new SqlParameter("@libelle", libelle), new SqlParameter("@estActive", active) }; } public void SetActive(int id) { ExecuteNonQuery("UPDATE AnneesAcademiques SET estActive=0; UPDATE AnneesAcademiques SET estActive=1 WHERE idAnnee=@id", new SqlParameter("@id", id)); } }
    public class EtudiantRepository : BaseRepository { protected override string TableName { get { return "Etudiants"; } } protected override string IdColumn { get { return "idEtudiant"; } } protected override string[] EditableColumns { get { return new[] { "matricule", "nom", "postnom", "prenom", "sexe", "dateNaissance", "adresse", "telephone" }; } } public SqlParameter[] Parameters(string matricule, string nom, string postnom, string prenom, string sexe, DateTime dateNaissance, string adresse, string telephone) { return new[] { new SqlParameter("@matricule", matricule), new SqlParameter("@nom", nom), new SqlParameter("@postnom", postnom), new SqlParameter("@prenom", prenom), new SqlParameter("@sexe", sexe), new SqlParameter("@dateNaissance", dateNaissance), new SqlParameter("@adresse", adresse), new SqlParameter("@telephone", telephone) }; } }
    public class InscriptionRepository : BaseRepository { protected override string TableName { get { return "Inscriptions"; } } protected override string IdColumn { get { return "idInscription"; } } protected override string[] EditableColumns { get { return new[] { "idEtudiant", "idPromotion", "idAnnee" }; } } protected override string SelectQuery { get { return "SELECT i.idInscription,i.idEtudiant,e.matricule,e.nom+' '+e.postnom+' '+e.prenom AS etudiant,i.idPromotion,p.nomPromotion,i.idAnnee,a.libelle FROM Inscriptions i INNER JOIN Etudiants e ON e.idEtudiant=i.idEtudiant INNER JOIN Promotions p ON p.idPromotion=i.idPromotion INNER JOIN AnneesAcademiques a ON a.idAnnee=i.idAnnee ORDER BY i.idInscription DESC"; } } public SqlParameter[] Parameters(int etudiant, int promotion, int annee) { return new[] { new SqlParameter("@idEtudiant", etudiant), new SqlParameter("@idPromotion", promotion), new SqlParameter("@idAnnee", annee) }; } }
    public class EnseignantRepository : BaseRepository { protected override string TableName { get { return "Enseignants"; } } protected override string IdColumn { get { return "idEnseignant"; } } protected override string[] EditableColumns { get { return new[] { "nom", "postnom", "prenom", "telephone", "specialite" }; } } public SqlParameter[] Parameters(string nom, string postnom, string prenom, string telephone, string specialite) { return new[] { new SqlParameter("@nom", nom), new SqlParameter("@postnom", postnom), new SqlParameter("@prenom", prenom), new SqlParameter("@telephone", telephone), new SqlParameter("@specialite", specialite) }; } }
    public class CoursRepository : BaseRepository { protected override string TableName { get { return "Cours"; } } protected override string IdColumn { get { return "idCours"; } } protected override string[] EditableColumns { get { return new[] { "nomCours", "coefficient", "idFaculte", "idPromotion" }; } } protected override string SelectQuery { get { return "SELECT c.idCours,c.nomCours,c.coefficient,c.idFaculte,f.nomFaculte,c.idPromotion,p.nomPromotion FROM Cours c INNER JOIN Facultes f ON f.idFaculte=c.idFaculte INNER JOIN Promotions p ON p.idPromotion=c.idPromotion ORDER BY c.idCours DESC"; } } public SqlParameter[] Parameters(string nom, decimal coef, int faculte, int promotion) { return new[] { new SqlParameter("@nomCours", nom), new SqlParameter("@coefficient", coef), new SqlParameter("@idFaculte", faculte), new SqlParameter("@idPromotion", promotion) }; } }
    public class AttributionCoursRepository : BaseRepository { protected override string TableName { get { return "AttributionsCours"; } } protected override string IdColumn { get { return "idAttribution"; } } protected override string[] EditableColumns { get { return new[] { "idCours", "idEnseignant" }; } } protected override string SelectQuery { get { return "SELECT a.idAttribution,a.idCours,c.nomCours,a.idEnseignant,e.nom+' '+e.postnom+' '+e.prenom AS enseignant FROM AttributionsCours a INNER JOIN Cours c ON c.idCours=a.idCours INNER JOIN Enseignants e ON e.idEnseignant=a.idEnseignant ORDER BY a.idAttribution DESC"; } } public SqlParameter[] Parameters(int cours, int enseignant) { return new[] { new SqlParameter("@idCours", cours), new SqlParameter("@idEnseignant", enseignant) }; } }
    public class NoteRepository : BaseRepository { protected override string TableName { get { return "Notes"; } } protected override string IdColumn { get { return "idNote"; } } protected override string[] EditableColumns { get { return new[] { "idEtudiant", "idCours", "note", "dateAjout" }; } } protected override string SelectQuery { get { return "SELECT n.idNote,n.idEtudiant,e.matricule,e.nom+' '+e.postnom+' '+e.prenom AS etudiant,n.idCours,c.nomCours,c.coefficient,n.note,n.dateAjout FROM Notes n INNER JOIN Etudiants e ON e.idEtudiant=n.idEtudiant INNER JOIN Cours c ON c.idCours=n.idCours ORDER BY n.idNote DESC"; } } public SqlParameter[] Parameters(int etudiant, int cours, decimal note, DateTime date) { return new[] { new SqlParameter("@idEtudiant", etudiant), new SqlParameter("@idCours", cours), new SqlParameter("@note", note), new SqlParameter("@dateAjout", date) }; } public DataTable GetByEtudiant(int idEtudiant) { return ExecuteTable(SelectQuery.Replace("ORDER BY n.idNote DESC", "WHERE n.idEtudiant=@idEtudiant ORDER BY c.nomCours"), new SqlParameter("@idEtudiant", idEtudiant)); } }
    public class UtilisateurRepository : BaseRepository { protected override string TableName { get { return "Utilisateurs"; } } protected override string IdColumn { get { return "idUser"; } } protected override string[] EditableColumns { get { return new[] { "username", "password", "role" }; } } public SqlParameter[] Parameters(string username, string password, string role) { return new[] { new SqlParameter("@username", username), new SqlParameter("@password", password), new SqlParameter("@role", role) }; } public DataTable Login(string username, string password) { return ExecuteTable("SELECT TOP 1 * FROM Utilisateurs WHERE username=@username AND password=@password", new SqlParameter("@username", username), new SqlParameter("@password", password)); } }
}
